### ISSUE TITLE
no ability to display images

### ISSUE THREAD

**Issue by mrbrdo** [jeremyevans/autoforme#1]
As far as I can see it is not possible to display an "image field" on the show/browse page. So e.g. I have a string column which is the filename of a file and I'd like to display this on the show/browse page. Is this planned to be supported? As far as I could see from the code it will either do it via the readonly Forme formatter which puts the value into a span but html-escapes it so I can't override that with the options, and on the browse it just uses column_value which also doesn't allow for any customization like that.

Thanks!

**Comment by jeremyevans** [comment]
Correct, this is not currently possible.  I think the easiest way to support it would be to add a new method.  Not sure what the method name should be (`value_html` is the best I think could think of).  For the show/browse/search_results pages, we call the method and if it returns non-nil, use the returned value instead of the current behavior.  How does that sound to you?

**Comment by mrbrdo** [comment]
yeah that sounds like it would work

**Comment by jeremyevans** [comment]
OK.  I'll see if I can work on this sometime soon.

**Comment by mrbrdo** [comment]
thanks!

**Comment by jeremyevans** [comment]
Can you please give the master branch a try?  Assuming it works for you, I'll push out a new gem version.

**Comment by mrbrdo** [comment]
seems to work yeah. thanks

**Comment by mrbrdo** [comment]
one more thing though, would it make sense to execute the proc in the context of the controller? in case of Rails, it would be nice to get access to the helpers (e.g. image_tag), this way I could even create a controller method like image_thumb and use that in my show_html blocks to reduce code duplication.

**Comment by jeremyevans** [comment]
The controller is accessible via the `request` argument (`request.controller`).  I don't want to do `instance_exec` tricks, it would be inconsistent with how the rest of AutoForme configuration works.

**Comment by mrbrdo** [comment]
Okay I think that works for now. I'll use ActionController::Base.helpers to call helpers.

The browse display works well, but the show ones get displayed above the item table, and have no label/title.
http://cl.ly/image/2a1W0m2F0R0p (see the two img tags at the top, where I would expect them to be in a table row)

**Comment by jeremyevans** [comment]
Since we are currently forcing table display in the show action, I agree that it should implicitly be wrapped in a table row.  I'll make that change soon.

**Comment by jeremyevans** [comment]
Change made at https://github.com/jeremyevans/autoforme/commit/0bee94c9bc921f8083ea2128bc7f33befcca4e96

**Comment by mrbrdo** [comment]
bundler is complaining. I have github master set for both forme and autoforme and I get this:
```
Bundler could not find compatible versions for gem "forme":
  In Gemfile:
    autoforme (>= 0) ruby depends on
      forme (>= 1.4.0) ruby

    forme (>= 0) ruby
```

**Comment by jeremyevans** [comment]
That's probably because forme's version hadn't been bumped to 1.4.0 yet in GitHub master.  I just pushed a commit that does that, hopefully that will make bundler happy.

**Comment by mrbrdo** [comment]
:+1: seems to be working now and table is displayed correctly
