### ISSUE TITLE
show page table columns

### ISSUE THREAD

**Issue by mrbrdo** [jeremyevans/autoforme#2]
I think there is an issue with the show page table, it has two columns but both the name and value of the attr seems to be output in the first column and the second column seems to be empty.
http://cl.ly/image/46460n0m3h3E

Sorry if I'm missing something.

**Comment by jeremyevans** [comment]
Ah, it should probably force the explicit labeler on the show page, to ensure that two columns are used.

**Comment by jeremyevans** [comment]
OK, this should be fixed.  Please let me know if you think any more changes should be made before the next release.

**Comment by mrbrdo** [comment]
We're using this at work, so will be working with it more next week. I'm not in a big hurry for a release.

**Comment by jeremyevans** [comment]
That's great.  I'm not in any hurry either, so please take your time and file issues for any bugs you find.

**Comment by mrbrdo** [comment]
this works now, thanks
