### ISSUE TITLE
Autoforme's models overrides custom Forme config

### ISSUE THREAD

**Issue by badosu** [jeremyevans/autoforme#4]
I use a special config to handle Bootstrap 3 forms with Forme, whenever I load autoforme it gets overriden by the default config, on my website and on the admin instead of just locally.

I was able to fix this by commenting this line: https://github.com/jeremyevans/autoforme/blob/master/lib/autoforme/models/sequel.rb#L14

On possible solution would be to ask the user to use the plugin explicitly when loading forme or checking if its already loaded, (e.g. by checking if it responds to `input_html`).

**Comment by jeremyevans** [comment]
Can you post a self contained example showing the problem?  AutoForme needs to make sure each Sequel model has the forme plugin loaded into it.  Loading the forme plugin should be idempotent, so loading it multiple times should not break anything.

I can't say for sure this isn't a bug, so I'll keep this open, but I need an example to test with.

**Comment by badosu** [comment]
@jeremyevans my problem is that I don't use the forme plugin for sequel, but rely instead on calling: `Sequel::Model.plugin Sequel::Plugins::BS3Forme
` where I define my own wrappers.

If it's a bug I don't, it depends on what's your mission with `autoforme`. As soon as I finish my current work I'll take a look on how to expose and approach this issue better.

Do as you please with this issue, as I said I am not sure if this is a problem with autoforme itself if it is not worried with flexibility.

**Comment by jeremyevans** [comment]
Yes, that's definitely not a bug, AutoForme is designed to depend on the forme plugin.  I'm guessing the BS3Forme plugin, if it is needed, should depend on the forme plugin, and then override the parts where it wants different behavior.

**Comment by badosu** [comment]
@jeremyevans Is there a possibility to expose an option to provide your own sequel plugin for forme? I believe this is important for autoforme to support multiple configurations, e.g. BS2 vs BS3

**Comment by jeremyevans** [comment]
The thing is, the configurations should never change the Sequel plugin, these should be configurations that are solely at the Forme level, not at the Sequel level.  I would opine that separate Sequel plugins for BS2 and BS3 means you are trying to fix something at the wrong level.

**Comment by badosu** [comment]
I find this affirmation strange, because at the sequel level the plugin defines how the labels are handled, in my case I need to internationalize this text, that's why I had to copy and patch the `forme` plugin, if there's another way to deal with this issue I'll be glad to change.

e.g. `handle_label` uses `#humanize` whereas I need to use `I18n.t("models.#{@obj.class.table_name}.#{f}")`.

**Comment by jeremyevans** [comment]
If the forme plugin is insufficient, we should handle that by making the plugin more flexible.  For example, allowing the user to override the `SequelInput` class.  So you could set:

```ruby
model.forme_input_class = SequelBS3Input
```

Ideally this `SequelBS3Input` class would subclass `SequelInput` and just overrode what it needed to.

Alternatively, I'm willing to consider an option for autoforme that could set so it would not automatically load the forme plugin.  If you think that's an easier approach, please submit a pull request.

**Comment by badosu** [comment]
Gotcha, would be willing to submit that patch, thanks for the feedback! I'll take a look later.
