### ISSUE TITLE
Error with inline_mtm_associations

### ISSUE THREAD

**Issue by brunoLehnen** [jeremyevans/autoforme#7]
I'm currently using autoforme with roda to develop an "admin" application in order to manage one of my company's application.

So, the error I'm reporting, first occurred to me when I was trying to make use of the inline_mtm_associations, I would always end up stuck with this exception: "SQLException: no such column".

My "admin" application, obviously, makes use of the same database structure as the main application, and, some of the tables in this database are actually not using an "id" column as the primary_key, in fact, some of the tables aren't even using Integers as primary key.

Stuck for a long time with this error, I proceeded to clone the repository and, using the demo_site, I started to investigate how autoforme actually performs the query for the inline_mtm_associations. 
In the beginning, when I first cloned, everything worked perfectly, but, as soon as I switched album's primary key to 'albumid' instead of 'id', I ended up with same exception when trying to enter album's edit page.
Autoforme was actually trying to use the left_primary_key in the "right table", thus, executing this query: "SELECT tags.* FROM tags WHERE (tags.albumid NOT IN (SELECT albums_tags.tag_id FROM albums_tags WHERE (albums_tags.album_id = 1)))"

So, I went through autoforme's code for a bit and noticed this method :
sequel.rb#unassociated_mtm_objects

In this method then, I spotted the following line:
ds = ds.exclude(S.qualify(ref.associated_class.table_name, model.primary_key)=>subquery)

By reading this line I got definitely convinced that the models were, in fact, being switched. With that in mind, I proceeded to replace "model.primary_key" with "ref.associated_class.primary_key" and everything started to work again.

It seems to me that things were actually working because, almost every time, both tables would use "id" as the primary key, so, even though the models were being switched, no conflicts were actually being generated.

**Comment by jeremyevans** [comment]
Thank you for the detailed analysis and fix.  I'll make this change and add appropriate tests, then push it up to GitHub.

**Comment by brunoLehnen** [comment]
I'm always glad to help.

**Comment by rosenfeld** [comment]
Hi @jeremyevans, would it be possible for you to release a new version with this patch? I'm basically waiting for it for a while before I merge a branch adding an admin interface to our app since I prefer to use a published gem than pointing to Github.

**Comment by jeremyevans** [comment]
@rosenfeld Definitely.  I was planning on releasing a new version of forme later today, and I'll see if I can also release a new version of autoforme today or tomorrow.

**Comment by rosenfeld** [comment]
Great! Thanks :)
